title: Home
description: My personal page
author: "Reach me at"
email: souzaamariana@gmail.com

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
avatar: "https://marianads.github.io/assets/imgs/me.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: https://marianads.github.io/assets/imgs/me.png
theme: minima

# Minima social links
twitter_username: desouzaamariana
linkedin_username: souzaamariana

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  skin: dark

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/CV.md
  - _pages/thesis.md
  - _pages/archive.md
  

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
